apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: reviews
  labels:
    app: reviews
    service: reviews
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: reviews